add_item:
  description: Adds an item to the schedule list.
  fields:
    name: {description: The name of the item to add., example: Beer}
enable_item:
  description: Marks an item as enabled in the schedule list
  fields:
    name: {description: The name of the item to mark as enabled., example: Beer}
